name: Plan infrastructure

on:
  pull_request:

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-3

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Tofu Init
        working-directory: terraform
        run: tofu init

      - name: Tofu Plan
        working-directory: terraform
        run: tofu plan -out=tfplan

      - name: Post plan comment
        uses: borchero/terraform-plan-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          terraform-cmd: tofu
          planfile: terraform/tfplan